ma_sv = input("Nhap ma sinh vien: ")
ho_ten = input("Nhap Ho Ten: ")
que = input("Nhap que quan: ")
nam_sinh = (input("Nhap nam sinh: "))
dtb = float(input("Nhap diem TB: "))
print(f"Ma SV: {ma_sv}")
print(f"Ho Ten: {ho_ten}")
print(f"Que Quan: {que}")
print(f"Diem TB: {dtb}")